In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
titanic_data=pd.read_csv("train.csv")

In [3]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
titanic_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit

split= StratifiedShuffleSplit (n_splits=1, test_size=0.2)

for train_indices, test_indices in split.split(titanic_data, titanic_data[["Survived", "Pclass", "Sex"]]):

    strat_train_set = titanic_data.loc[train_indices]

    strat_test_set = titanic_data.loc[test_indices]

In [6]:
strat_train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 122 to 720
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Name         712 non-null    object
 4   Sex          712 non-null    object
 5   Age          569 non-null    float64
 6   SibSp        712 non-null    int64
 7   Parch        712 non-null    int64
 8   Ticket       712 non-null    object
 9   Fare         712 non-null    float64
 10  Cabin        162 non-null    object
 11  Embarked     710 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 72.3+ KB

In [7]:
from sklearn.base import BaseEstimator, TransformerMixin 
from sklearn.impute import SimpleImputer

class AgeImputer (BaseEstimator, TransformerMixin):
    def fit(self, x, y=None): 
        return self
    def transform(self, X):
        imputer=SimpleImputer ( strategy="mean")
        X['Age'] = imputer.fit_transform (X[['Age']])
        return X

In [8]:
from sklearn.preprocessing import OneHotEncoder

class FeatureEncoder (BaseEstimator, TransformerMixin):

    def fit (self, x, y=None):
        return self

    def transform(self, X):
        encoder = OneHotEncoder() 
        matrix = encoder.fit_transform (X[ ['Embarked']]).toarray()
        column_names = ["I", "s", "Q", "N"]
        for i in range (len (matrix. T)):
            X[column_names[i]] = matrix.T[i]
        matrix = encoder.fit_transform (X[['Sex']]).toarray ()
        column_names = ["Female", "Male"]
        for i in range (len (matrix.T)):
            X[column_names[i]] = matrix.T[i]
        return X

In [9]:
class FeatureDropper (BaseEstimator, TransformerMixin):

    def fit (self, X, y=None):

        return self

    def transform (self, X):

        return X.drop(["Embarked", "Name", "Ticket", "Cabin", "Sex", "N"], axis=1, errors="ignore")

In [10]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline ([("ageimputer", AgeImputer()), ("featureencoder", FeatureEncoder()), ("featuredropper", FeatureDropper ())])

In [11]:
strat_train_set = pipeline.fit_transform(strat_train_set)

In [12]:
strat_train_set

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,I,s,Q,Female,Male
122,123,0,2,32.500000,1,0,30.0708,1.0,0.0,0.0,0.0,1.0
249,250,0,2,54.000000,1,0,26.0000,0.0,0.0,1.0,0.0,1.0
252,253,0,1,62.000000,0,0,26.5500,0.0,0.0,1.0,0.0,1.0
832,833,0,3,29.148225,0,0,7.2292,1.0,0.0,0.0,0.0,1.0
266,267,0,3,16.000000,4,1,39.6875,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
22,23,1,3,15.000000,0,0,8.0292,0.0,1.0,0.0,1.0,0.0
164,165,0,3,1.000000,4,1,39.6875,0.0,0.0,1.0,0.0,1.0
163,164,0,3,17.000000,0,0,8.6625,0.0,0.0,1.0,0.0,1.0
749,750,0,3,31.000000,0,0,7.7500,0.0,1.0,0.0,0.0,1.0
720,721,1,2,6.000000,0,1,33.0000,0.0,0.0,1.0,1.0,0.0

In [13]:
strat_train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 122 to 720
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Age          712 non-null    float64
 4   SibSp        712 non-null    int64
 5   Parch        712 non-null    int64
 6   Fare         712 non-null    float64
 7   I            712 non-null    float64
 8   s            712 non-null    float64
 9   Q            712 non-null    float64
 10  Female       712 non-null    float64
 11  Male         712 non-null    float64
dtypes: float64(7), int64(5)
memory usage: 72.3 KB

In [14]:
from sklearn.preprocessing import StandardScaler

X = strat_train_set.drop(['Survived'], axis=1)
y = strat_train_set['Survived']

scaler=StandardScaler ()
X_data = scaler.fit_transform (X)
y_data=y.to_numpy()

In [15]:
from sklearn.ensemble import RandomForestClassifier 
from sklearn.model_selection import GridSearchCV

clf = RandomForestClassifier()
param_gird = [
    {"n_estimators": [10, 100, 200, 500], "max_depth": [None, 5, 10], "min_samples_split": [2,3,4]}
     ]

grid_search= GridSearchCV (clf, param_gird, cv=3, scoring="accuracy", return_train_score=True) 
grid_search.fit (X_data, y_data)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid=[{'max_depth': [None, 5, 10],
                          'min_samples_split': [2, 3, 4],
                          'n_estimators': [10, 100, 200, 500]}],
             return_train_score=True, scoring='accuracy')

In [16]:
final_clf = grid_search.best_estimator_

In [17]:
 final_clf

RandomForestClassifier(max_depth=5, n_estimators=200)

In [18]:
strat_test_set = pipeline.fit_transform (strat_test_set)

In [19]:
X_test = strat_test_set.drop(['Survived'], axis=1) 
y_test=strat_test_set['Survived']
scaler=StandardScaler ()
X_data_test = scaler.fit_transform (X_test)
y_data_test = y_test.to_numpy()

In [20]:
final_clf.score(X_data_test,y_data_test)

0.8212290502793296

In [21]:
final_data=pipeline.fit_transform(titanic_data)

In [22]:
final_data

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,I,s,Q,Female,Male
0,1,0,3,22.000000,1,0,7.2500,0.0,0.0,1.0,0.0,1.0
1,2,1,1,38.000000,1,0,71.2833,1.0,0.0,0.0,1.0,0.0
2,3,1,3,26.000000,0,0,7.9250,0.0,0.0,1.0,1.0,0.0
3,4,1,1,35.000000,1,0,53.1000,0.0,0.0,1.0,1.0,0.0
4,5,0,3,35.000000,0,0,8.0500,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.000000,0,0,13.0000,0.0,0.0,1.0,0.0,1.0
887,888,1,1,19.000000,0,0,30.0000,0.0,0.0,1.0,1.0,0.0
888,889,0,3,29.699118,1,2,23.4500,0.0,0.0,1.0,1.0,0.0
889,890,1,1,26.000000,0,0,30.0000,1.0,0.0,0.0,0.0,1.0
890,891,0,3,32.000000,0,0,7.7500,0.0,1.0,0.0,0.0,1.0

In [23]:
X_final=final_data.drop(['Survived'],axis=1)
y_final=final_data['Survived']
scaler=StandardScaler()
X_data_final=scaler.fit_transform(X_final)
y_data_final=y_final.to_numpy()

In [24]:
prod_clf = RandomForestClassifier()
param_gird = [
    {"n_estimators": [10, 100, 200, 500], "max_depth": [None, 5, 10], "min_samples_split": [2,3,4]}
]
grid_search= GridSearchCV (prod_clf, param_gird, cv=3, scoring="accuracy", return_train_score=True)
grid_search.fit (X_data_final, y_data_final)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid=[{'max_depth': [None, 5, 10],
                          'min_samples_split': [2, 3, 4],
                          'n_estimators': [10, 100, 200, 500]}],
             return_train_score=True, scoring='accuracy')

In [25]:
prod_final_clf =grid_search.best_estimator_

titanic_test_data = pd.read_csv("test.csv")

final_test_data = pipeline.fit_transform(titanic_test_data)

In [26]:
X_final_test = final_data 
X_final_test=X_final.fillna(method='ffill')
scaler=StandardScaler()
X_datafinal_test=scaler.fit_transform(X_final_test)

In [27]:
predictions=prod_final_clf.predict(X_data_test)

In [28]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0], dtype=int64)